#pragma once
void test_constructor1();
void test_constructor2();
void test_insert1();
void test_insert2();
void test_insert3();
void test_FindMin1();
void test_FindMin2();
void test_countNodes1();
void test_countNodes2();
void test_countEdges1();
void test_countEdges2();
void test_height1();
void test_height2();
void testAll();